---
- name: Reboot all nodes
  hosts: ardana-{{ clm_env }}
  remote_user: root
  gather_facts: False

  tasks:

  - include: _get_ansible_hosts.yml

  - name: Reboot deployer node
    include: reboot-node.yml
    vars:
      ansible_node: "{{ ardana_ansible_deployer }}"
      node_is_deployer: true

  - name: Reboot controller nodes
    include: reboot-node.yml
    vars:
      ansible_node: "{{ item }}"
      node_is_deployer: false
    when: item != ardana_ansible_deployer
    with_items: "{{ ardana_ansible_controllers }}"

  - name: Reboot remaining nodes
    include: reboot-node.yml
    vars:
      ansible_node: "{{ item }}"
      node_is_deployer: false
    when: item != ardana_ansible_deployer and
          item not in ardana_ansible_controllers
    with_items: "{{ ardana_ansible_nodes }}"

  - name: Run a global service status check
    shell: |
      ansible-playbook -v -i hosts/verb_hosts ardana-status.yml
    args:
      chdir: /var/lib/ardana/scratch/ansible/next/ardana/ansible
    become: true
    become_user: ardana

