---
- name: Setup SSH keys
  hosts: hosts
  gather_facts: False

  tasks:
  - name:  Write available ssh keys to people can login
    become: yes
    lineinfile:
      dest: /root/.ssh/authorized_keys
      line: "{{ item }}"
    with_items:
      # aplanas
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdP6oez825gnOLVZu70KqJXpqL4fGfaFNk87GSk3xLRjixGtr013+hcN03ZRKU0/2S7J0T/dICc2dhG9xAqa/A31QachQeg2RhPxM2SL+wgzx0geDmf6XDhhe8reos5jgzw6Pq59gyWfurlZaMEZAoOYkfNb5OG4vQQN8Z7hldx+DBANPbylApurVz6h5vvRrkPfuRVN5ZxOkI+LeWhpovX5XK3eTjetAwWEro6AAXpGoQQQDjSOoYHCUmXzcZkmIWEubCZvAI4RZ+XCZs+wTeO2RIRsunqP8J+XW4cZ28RZBc9K4I1BV8C6wBxN328LRQcilzw+Me+LfreeDPglqx aplanas@g227
      # colleen
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAGh98q+aKxLXnWYmRwPIBv1GXMvNfSQlbViNs1vjVmQytYz0dcuxcgT2FRsh3/h4A9HLXcpVksj89qEglEq+B2sqGvEbwl7Pm5/+8EI2a45XwUbf7iwAjHq9swOdmm45QRoogbYuw1PBQzVrkcHUSrhr0j1J+CWgfs4ufsB8yYJkSr4G+h/SXsvu9Otd2e2tODcP0vnKpOgI2cSwaq8g99+kENF4JmxQT51iEtS/hTnJgZj8UJw1vTfJoDQB5Kye56w/J30wD1IrSPNNg5OvgDanM6aGBYTLXVKXb5qcPdSAnxBxjDrr9I8WYSlPH48a5E/1Tv0d/U42jxg/XT4hXJbkbhzBjv1gdkzgAZ6QPg0YvXeWGlTrriaahrl6Dohxv043zePVDNakqdqi4eWBM2Vg4CCeUEUwajsgr4vAdsCcwGhqQgRjO4BMbTY3BpbWi4/ECnY3UpAWLg+Ab6YVDMkBh7HVOyNmiT03GYgn0yaB/ZwimWikUVQWUvh1semLy53jslajG5PiSr/RqfkOQfmo4TSWrfflJRJBfLvVvmb6W2Mir6iyPyrNl/8bWehKBgAaM/3l4SbTsq7wZ3nIfztNQDzKdwVL3U1cZDWWq+KuS7AzJo3PBDCcxnn2149lyUfi5C14AzFXYrYUcTXnhdgMHnR7Ye5W5q4u1vhTL5Q== colleen@moose
      # dmueller
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG6JHF/jzetTlV4YgjlNrx0BRh/aAuSW13dxYJpLakBx dmueller@oldboy
      # tbechtold
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2mEyxfkW1u84u5BocLCAXESj2qObWkxUd20cmPolhJYlIWLOafa69Dw5A9CjFBp0U6Jx5d0JWcwmAc5ZeffQ7t7vzmtHCZnpKkyZhN9bu6vuCh4N+I643SI/K7tdbB2E8ZE6uI7ORMAan5+t0bNSVolUVq6X1w7dIA5El54K10WNdiwgRKW6e3anNbJ3rBLGEk7gawZqDDOqTvVQmOBGWek3BjSReDvg3rkmTQLxJkiKdxnx4/s7gzH1xTpsS/OludIuSxF0BK064ZcT1t09qcjnT4Os1inV2GfYswt+UhpgqrHqXjEs0Z3y4Oy77QBKL1rDf93CP4a4+eJjqXe+v tbechtold@suse.com
      # jtomasiak
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5pApJQ6rC+KAMSeXSLhqJTTcyNKrl7EU41XYzJoj0/AmwNtAt4eVNwVgJ3q0Uvw8DUtSYrb6d6jQCzsm4qdpc7dk1u8lIIYOlv/QYveAnsfkQTslocXZBsgBNcEUNguVVutUWDux4q/O5y8VU7wIr+5KtnEuFNO6V1h0TrC6wP+TcHCC5NnESBj/RHUkQc22xuc19HR/1pJf9WrUz+1pSK8dD96ckPIs3H6E0U6uVYuqn7GT9KeETxPKYZhs2qtwS/BBxtZZ/BbXQtzF0yHkLPBnutdIwcG74TF7QAAsECTkAsMi0FdABJeLTQA/7i7tv/KNBiHmf0wH9eHuGdXHx jtomasiak@suse.com
      # rhafer
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAs7yO31aVTHrbX+b9vTQfcQPoFQibqo53itd0RyyEl3IXVJR2jHN6rxia3/CkBItkr0F9sS3Rk+KfiWoFJgs+1qAm88FmhY2/9Xza1b6n99s1UCXXurziqeKV0x97vbbFVsDB5bAGPSoIwDWVcs7MF9H5CjHJGP16BnLSxi1VNUM= rhafer@suse.com
      # sjamgade
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDULOj/wmWiazF7zN2Q3nDxos7oW+du7wcKe+jn6PzAbb6dhVem/JCwiAgG4NiQFH2ZkAAxO3T1LtBfNxveMa8wQRiHtbhz/iFJNJ0WD0VDE/S+wSodzxnBtIyR071Mn4jO1xl1MfVUmc/qAhiNV+hkUgs4FoGNzrIuzUZAVLlRklUAGDposK6SchXIAXyYjVg7Q5Qx89oD1zvchHsyg77x3okLhtHVz8CjzkQYguIR6RsXYH9yPFrbK5EM9+4YeE2XRbzhtYhTgsNP29nBPg+vBSovFYa45YE5WKe8GHz4tqk0FcImwhY5ytmkZDCNKdQVEfFw88KEtYxqZW4gwxyf sjamgade@suse.com
