---
- name: Install package updates on all nodes
  hosts: ardana-virt
  remote_user: root
  gather_facts: False

  vars:
    update_method: update
    update_gpg_checks: true
    update_licenses_agree: true
    update_include_reboot_patches: true

  tasks:

  - include: _get_ansible_hosts.yml

  - name: Update deployer node
    include: update-node.yml
    vars:
      ansible_node: "{{ ardana_ansible_deployer }}"
      node_is_deployer: true

  - name: Update controller nodes
    include: update-node.yml
    vars:
      ansible_node: "{{ item }}"
      node_is_deployer: false
    when: item != ardana_ansible_deployer
    with_items: "{{ ardana_ansible_controllers }}"

  - name: Update remaining nodes
    include: update-node.yml
    vars:
      ansible_node: "{{ item }}"
      node_is_deployer: false
    when: item != ardana_ansible_deployer and
          item not in ardana_ansible_controllers
    with_items: "{{ ardana_ansible_nodes }}"

  - name: Run a global service status check
    shell: |
      ansible-playbook -v -i hosts/verb_hosts ardana-status.yml
    args:
      chdir: /var/lib/ardana/scratch/ansible/next/ardana/ansible
    become: true
    become_user: ardana

