#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

clm_service_components:
  - lifecycle-manager
  - tempest
  - openstack-client
  - ceilometer-client
  - cinder-client
  - designate-client
  - glance-client
  - heat-client
  - ironic-client
  - keystone-client
  - magnum-client
  - neutron-client
  - nova-client
  - swift-client
  - monasca-client
  - barbican-client
  - ntp-client

clm_flavor: cloud-ardana-job-compute
controller_flavor: cloud-ardana-job-controller
compute_flavor: cloud-ardana-job-compute
sles_images:
  cloud8: cleanvm-jeos-SLE12SP3
  cloud9: cleanvm-jeos-SLE12SP4
sles_image: "{{ sles_images[cloud_release] }}"
rhel_image: centos73
disk_size: 30

images:
  CONTROLLER-ROLE: '{{ sles_image }}'
  STD-CONTROLLER-ROLE: '{{ sles_image }}'
  STD-COMPUTE-ROLE:
      sles12sp3-x86_64: '{{ sles_images["cloud8"] }}'
      sles12sp4-x86_64: '{{ sles_images["cloud9"] }}'
      rhel73-x86_64: '{{ rhel_image }}'
  COMPUTE-ROLE:
      sles12sp3-x86_64: '{{ sles_images["cloud8"] }}'
      sles12sp4-x86_64: '{{ sles_images["cloud9"] }}'
      rhel73-x86_64: '{{ rhel_image }}'

flavors:
  CONTROLLER-ROLE: '{{ controller_flavor }}'
  STD-CONTROLLER-ROLE: '{{ controller_flavor }}'
  STD-COMPUTE-ROLE: '{{ compute_flavor }}'
  COMPUTE-ROLE: '{{ compute_flavor }}'

disks:
  CONTROLLER-DISKS:
    default: 10 # swift-object (vdc-vdf)
    vdb: 20 # cinder-volume

