#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

rc_task: "{{ task }}"
rc_domain: "chat.suse.de"
rc_protocol: "https"
rc_url: "{{ rc_protocol }}://{{ rc_domain }}"
rc_token: ""
rc_bot:
  username: ""
  password: ""

rc_auth_info_git_url: "https://gitlab.suse.de/cloud-qe/ardana-bm-info.git"
rc_auth_info_dir: "/tmp/ardana-bm-info"

rc_channel: "{{ is_physical_deploy | ternary(rc_channels[ardana_env], '@' ~ ardana_env.split('-')[0]) }}"

rc_channel_id_query: "json.channels[?name=='{{ rc_channels[ardana_env] }}']._id"

rc_deploy_announcement_file: "~/deploy_finished-{{ ardana_env }}.rc"

rc_msg_title: "{{ rc_task | upper }} {{ rc_action }}"
rc_msg_color: "{{ 'danger' if rc_state == 'Failed' else 'good' if rc_state == 'Success' else '#BDC3C7' }}"

# IVerify vars
iverify_failed_tests:
  stdout: "Not available"

# Tempest vars
tempest_run_filter: "smoke"
os_health_server: "10.86.0.167"
os_health_url: "http://{{ os_health_server }}/#/job/{{ os_health_build_name }}"
os_health_url_msg: "[{{ os_health_url }}]({{ os_health_url }})"

ansible_log_url: "{{ lookup('env', 'BUILD_URL') }}artifact/.artifacts/ansible.log"
ansible_log_url_msg: "[{{ ansible_log_url }}]({{ ansible_log_url }})"
ansible_log_stream: "http://{{ hostvars[ardana_env].ansible_host if ardana_env in groups['all'] else 'NA' }}:9091/"
ansible_log_stream_msg: "[{{ ansible_log_stream }}]({{ ansible_log_stream }})"
jenkins_build_url: "{{ lookup('env', 'BUILD_URL') }}"
jenkins_build_url_msg: "{{ (jenkins_build_url != '') | ternary('[' ~ jenkins_build_url ~ '](' ~ jenkins_build_url ~ ')', lookup('env', 'USER')) }}"

rc_im_name: "{{ (scenario_name == '') | ternary(model, scenario_name) }}"
