---
service_groups:
  - name: clm
    type: cluster
    prefix: c0
    heat_flavor_id: "{{ vcloud_flavor_name_prefix }}-compute"
    member_count: '{{ (clm_model == "standalone") | ternary(1, 0) }}'
    service_components:
      - CLM
  - name: mml-core
    type: cluster
    prefix: c1
    heat_flavor_id: "{{ vcloud_flavor_name_prefix }}-controller"
    member_count: '{{ core_nodes|default(2) }}'
    service_components:
      - '{{ (clm_model == "integrated") | ternary("CLM", '') }}'
      - CORE
      - SWPAC
      - SWOBJ
      - NEUTRON
  - name: lmm
    type: cluster
    prefix: lmm
    heat_flavor_id: "{{ vcloud_flavor_name_prefix }}-compute"
    member_count: '{{ lmm_nodes|default(3) }}'
    service_components:
      - LMM
  - name: dbmq
    type: cluster
    prefix: dbmq
    heat_flavor_id: "{{ vcloud_flavor_name_prefix }}-minimal"
    member_count: '{{ dbmq_nodes|default(3) }}'
    service_components:
      - DBMQ
  - name: compute
    type: resource
    prefix: sles-comp
    heat_flavor_id: "{{ vcloud_flavor_name_prefix }}-compute"
    member_count: '{{ computes|default(1) }}'
    min_count: 0
    service_components:
      - COMPUTE
  - name: rhel-compute
    type: resource
    prefix: rhel-comp
    distro_id: rhel73-x86_64
    heat_flavor_id: "{{ vcloud_flavor_name_prefix }}-compute"
    member_count: '{{ rhel_computes|default(1) }}'
    min_count: 0
    service_components:
      - COMPUTE
