#
# (c) Copyright 2019 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- import_playbook: _create-vcloud-inventory.yml

- name: Run tempest and collect results
  hosts: "controller[0]"
  remote_user: root
  gather_facts: True
  vars:
    task: "tempest"

  pre_tasks:
    - include_role:
        name: rocketchat_notify
      vars:
        rc_action: "started"
        rc_state: "Started"
      when: rc_notify

  tasks:
    - block:
        - include_role:
            name: crowbar_tempest
            public: yes

        - include_role:
            name: tempest_results
            public: yes

      rescue:
        - include_role:
            name: rocketchat_notify
          vars:
            rc_action: "finished"
            rc_state: "Failed"
          when: rc_notify

        - name: Stop if something failed
          fail:
            msg: "{{ task }} failed."

      always:
        - include_role:
            name: jenkins_artifacts
          vars:
            jenkins_artifacts_to_collect:
              - src: "{{ tempest_results_log }}"
              - src: "{{ tempest_results_subunit }}"
              - src: "{{ subunit_xml_results }}"
              - src: "{{ subunit_html_results }}"
          when: lookup("env", "WORKSPACE")

  post_tasks:
      - include_role:
          name: rocketchat_notify
        vars:
          rc_action: "finished"
          rc_state: "{{ (tempest_test_results.failed | int > 0) | ternary('Failed', 'Success' ) }}"
        when: rc_notify
