# Use this playbook for quick tests of the post-deployment checks
# without having to repeatedly go through a full deployment.  This
# assumes you already have a deployment which got as far as finishing
# the pre-deploy-checks.yml playbook and (at least partially)
# deploying Ardana.
#
# Run it from the same environment in which the original deployment
# was run, via:
#
#   ansible-playbook \
#     -e verification_temp_dir=/tmp/ardana-job-rpm-verification.XXXXXXXX \
#     test-post-deployment-checks.yml
#
# replacing XXXXXXXX with whichever temporary directory was already
# written to.

---
- name: Test post-deployment checks
  hosts: ardana-{{ cloud_env }}
  remote_user: root
  gather_facts: False
  vars:
    rpm_verification_test_mode:
      true
    pre_deploy_unowned_files:
      "{{ verification_temp_dir }}/rpm-qf-pre.out"
    pre_deploy_rpm_verification:
      "{{ verification_temp_dir }}/rpm-verify-pre.out"
    failures:
      []

  tasks:
  - name: Check verification_temp_dir is defined
    fail: msg="Pass -e verification_temp_dir=/tmp/... when running this playbook"
    when: verification_temp_dir is not defined

  - include: post-deploy-checks.yml

  # If you change the below, also change init.yml to match!

  - name: Record any failures of post-deployment checks
    set_fact:
      failures: "{{ failures + post_deploy_checks_failures }}"

  - name: Report any failures
    fail:
      msg: |
        {{failures|length}} failures:
        {% for failure in failures %}
        {{ failure }}
        {% endfor %}
    when: failures|length > 0
