#
# (c) Copyright 2015,2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
  product:
    version: 2

  disk-models:
  - name: CONTROLLER-DISKS
    # 6 disk node; first disk holds VG with logical volumes for all services
    # other than swift & cinder. Cinder gets second disk for it's LVM backing
    # store, and Swift gets remaining 4 for object storage.
    device-groups:
      - name: cinder-volume
        devices:
          - name: /dev/vdb
        consumer:
          name: cinder
      - name: swiftobj
        devices:
          - name: /dev/vdc
          - name: /dev/vdd
          - name: /dev/vde
          - name: /dev/vdf
        consumer:
          name: swift
          attrs:
            rings:
              - account
              - container
              - object-0
              - object-1
    volume-groups:
    # The policy is not to consume 100% of the space of each volume group.
    # 5% should be left free for snapshots and to allow for some flexibility.
    # sda_root is a templated value to align with whatever partition is really used
    # This value is checked in os config and replaced by the partition actually used
    # on sda e.g. sda1 or sda5

      - name: ardana-vg
        physical-volumes:
          - /dev/vda_root
        logical-volumes:
          - name: root
            size: 35%
            fstype: ext4
            mount: /

          - name: log
            size: 17%
            mount: /var/log
            fstype: ext4
            mkfs-opts: -O large_file

          - name: crash
            size: 2%
            mount: /var/crash
            fstype: ext4
            mkfs-opts: -O large_file

          - name: elasticsearch
            size: 10%
            mount: /var/lib/elasticsearch
            fstype: ext4
            mkfs-opts: -O large_file

          - name: mysql
            size: 5%
            mount: /var/lib/mysql
            fstype: ext4
            mkfs-opts: -O large_file
            consumer:
              name: mysql

          - name: cassandra_db
            size: 5%
            mount: /var/cassandra/data
            fstype: ext4
            mkfs-opts: -O large_file
            consumer:
              name: cassandra

          - name: cassandra_log
            size: 3%
            mount: /var/cassandra/commitlog
            fstype: ext4
            mkfs-opts: -O large_file
            consumer:
              name: cassandra

          - name: kafka
            size: 5%
            mount: /var/kafka
            fstype: ext4
            mkfs-opts: -O large_file
            consumer:
              name: kafka

          - name: rabbitmq
            size: 10%
            mount: /var/lib/rabbitmq
            fstype: ext4
            mkfs-opts: -O large_file
            consumer:
              name: rabbitmq
              rabbitmq_env: home

          - name: zookeeper
            size: 2%
            mount: /var/lib/zookeeper
            fstype: ext4
            mkfs-opts: -O large_file

        consumer:
          name: os

    # Cinder: cinder volume needs temporary local filesystem space to convert
    # images to raw when creating bootable volumes. Using a separate volume
    # will both ringfence this space and avoid filling /
    # The size should represent the raw size of the largest image times
    # the number of concurrent bootable volume creations.
    # The logical volume can be part of an existing volume group or a
    # dedicated volume group.
    #  - name: cinder-vg
    #    physical-volumes:
    #      - /dev/vdx
    #    logical-volumes:
    #     - name: cinder_image
    #       size: 5%
    #       mount: /var/lib/cinder
    #       fstype: ext4

    # Glance cache: if a logical volume with consumer usage 'glance-cache'
    # is defined Glance caching will be enabled. The logical volume can be
    # part of an existing volume group or a dedicated volume group.
    # - name: glance-vg
    #   physical-volumes:
    #     - /dev/vdx
    #   logical-volumes:
    #     - name: glance-cache
    #       size: 95%
    #       mount: /var/lib/glance/cache
    #       fstype: ext4
    #       mkfs-opts: -O large_file
    #       consumer:
    #         name: glance-api
    #         usage: glance-cache
