#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
username: barbican_qe_admin
password: barbican_qe_admin
project_name: barbican_qe_admin_project

service_type: key-manager
service_name: barbican
region_name: region1
endpoint_type: internal
server_host_href_set: False

service_admin: barbican_qe_service_admin
service_admin_project: barbican_qe_service_admin_project
service_admin_password: barbican_qe_service_admin

#Projects
project_a: barbican_project_a
project_b: barbican_project_b

# users for project_a
admin_a: barbican_project_a_admin
admin_a_password: barbican
creator_a: barbican_project_a_creator
creator_a_password: barbican
observer_a: barbican_project_a_observer
observer_a_password: barbican
auditor_a: barbican_project_a_auditor
auditor_a_password: barbican

# Another creator user for project_a due to changes in review 120282
creator_a_2: barbican_project_a_creator_2
creator_a_2_password: barbican

# users for project_b
admin_b: barbican_project_b_admin
admin_b_password: barbican
creator_b: barbican_project_b_creator
creator_b_password: barbican
observer_b: barbican_project_b_observer
observer_b_password: barbican
auditor_b: barbican_project_b_auditor
auditor_b_password: barbican

#Quotas
# default number of secrets allowed per project
quota_secrets: -1
# default number of orders allowed per project
quota_orders: -1
# default number of containers allowed per project
quota_containers: -1
# default number of consumers allowed per project
quota_consumers: -1
# default number of CAs allowed per project
quota_cas: -1


test_run_filter: "{{ run_filter | default('smoke', true) }}"
run_concurrency: 0
ca_bundle: /etc/ssl/ca-bundle.pem
#Overrides
ardana_qe_tests_git_url: "{{ ardana_qe_tests_git_repo }}/openstack/barbican"
ardana_qe_tests_dir: "{{ ardana_qe_test_work_dir }}"

#For now setting this to stable/pike. We need to update this based on the cloud
# release version as part of the framework.
ardana_qe_tests_branch: "stable/pike"
ardana_qe_test_get_failed_cmd: "grep -B1 -- '------' {{ ardana_qe_test_log }} |
  awk -F '\n' 'ln ~ /^$/ { ln = \"matched\"; print $1 } $1 ~ /^--$/ { ln = \"\" }'"
  
ardana_qe_test_venv_requires:
  - 'os-testr'
ardana_qe_test_run_filters: "{{ role_path }}/files/run_filters/"
os_resources_requires:
  - 'user'
  - 'project'

os_resource_test_auth:
  - username: "{{ username }}"
    password: "{{ password }}"
    project: "{{ project_name }}"
    role: "key-manager:admin"
  - username: "{{ service_admin }}"
    password: "{{ service_admin_password }}"
    project: "{{ service_admin_project }}"
    role: "key-manager:service-admin"
  - username: "{{ admin_a }}"
    password: "{{ admin_a_password }}"
    project: "{{ project_a }}"
    role: "key-manager:admin"
  - username: "{{ creator_a }}"
    password: "{{ creator_a_password }}"
    project: "{{ project_a }}"
    role: "key-manager:creator"
  - username: "{{ creator_a_2 }}"
    password: "{{ creator_a_2_password }}"
    project: "{{ project_a }}"
    role: "key-manager:creator"
  - username: "{{ observer_a }}"
    password: "{{ observer_a_password }}"
    project: "{{ project_a }}"
    role: "key-manager:observer"
  - username: "{{ auditor_a }}"
    password: "{{ auditor_a_password }}"
    project: "{{ project_a }}"
    role: "key-manager:auditor"
  - username: "{{ username }}"
    password: "{{ password }}"
    project: "{{ project_b }}"
    role: "key-manager:admin"
  - username: "{{ admin_b }}"
    password: "{{ admin_b_password }}"
    project: "{{ project_b }}"
    role: "key-manager:admin"
  - username: "{{ creator_b }}"
    password: "{{ creator_b_password }}"
    project: "{{ project_b }}"
    role: "key-manager:creator"
  - username: "{{ observer_b }}"
    password: "{{ observer_b_password }}"
    project: "{{ project_b }}"
    role: "key-manager:observer"
  - username: "{{ auditor_b }}"
    password: "{{ auditor_b_password }}"
    project: "{{ project_b }}"
    role: "key-manager:auditor"
