#
# (c) Copyright 2019 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
#
# Standard scenario service template with standalone CLM node: all services enabled
# and variable number of controller, SLES compute and RHEL compute nodes.
#
# Template parameters:
#   controllers: number of controller nodes (default: 3)
#   sles_computes: number of SLES compute nodes (default: 1)
#   rhel_computes: number of RHEL compute nodes (default: 1)
#
---

service_groups:
  - name: clm
    type: cluster
    prefix: c0
    heat_flavor_id: "{{ vcloud_flavor_name_prefix }}-compute"
    member_count: '{{ (clm_model == "standalone") | ternary(1, 0) }}'
    service_components:
      - CLM
  - name: controller
    type: cluster
    prefix: c1
    heat_flavor_id: "{{ vcloud_flavor_name_prefix }}-controller"
    member_count: '{{ controllers|default(3) }}'
    service_components:
      - '{{ (clm_model == "integrated") | ternary("CLM", '') }}'
      - CORE
      - LMM
      - DBMQ
      - SWPAC
      - NEUTRON
      - SWOBJ
  - name: sles-compute
    type: resource
    prefix: sles-comp
    heat_flavor_id: "{{ vcloud_flavor_name_prefix }}-compute"
    member_count: '{{ sles_computes|default(1) }}'
    min_count: 0
    service_components:
      - COMPUTE
  - name: rhel-compute
    type: resource
    prefix: rhel-comp
    distro_id: "{{ rhel_distro_id }}"
    heat_flavor_id: "{{ vcloud_flavor_name_prefix }}-compute"
    member_count: '{{ rhel_computes|default(1) }}'
    min_count: 0
    service_components:
      - RHEL_COMPUTE
