#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

# Announcement
rc_announcement_started: "Deployment in PROGRESS: {{ _announcement_full }}"
rc_announcement_finished: "{{ 'READY FOR TESTING: ' if rc_state == 'Success' else 'Deployment FAILED: ' }} {{ _announcement_full }}"

_announcement_full: "{{ _announcement_data + _announcement_mu if _mu_available else _announcement_data }}"

_announcement_data: "{{ cloudsource }} - {{ rc_im_name }}{{ _announcement_ses }}"
_announcement_mu: "{{ ' - MU: ' + maint_updates if maint_updates is defined else '' }}"

_announcement_ses: "{{ ses_enabled | ternary('-SES', '') }}"

# Chat message
rc_msg_fields_started: "{{ _msg_fields_started + _msg_field_mu + _msg_field_clm_nodes }}"
rc_msg_fields_finished: "{{ _msg_fields_finished + _msg_field_mu + _msg_field_clm_nodes }}"

_msg_ses_enabled: "{{ ses_enabled | ternary('Yes', 'No') }}"
_msg_fields_started:
  - title: Started by
    value: "{{ jenkins_build_url_msg }}"
    short: False
  - title: Ardana log stream
    value: "{{ ansible_log_stream_msg if cloud_env in groups['all'] else 'NA' }}"
    short: False
  - title: Deployer
    value: "{{ hostvars[cloud_env].ansible_host if cloud_env in groups['all'] else 'NA' }}"
    short: True
  - title: cloudsource
    value: "{{ cloudsource }}"
    short: True
  - title: Input model
    value: "{{ rc_im_name }}"
    short: True
  - title: SES enabled
    value: "{{ _msg_ses_enabled }}"
    short: True

_msg_fields_finished:
  - title: Built by
    value: "{{ jenkins_build_url_msg }}"
    short: False
  - title: Media version
    value: "{{ cloud_media_build_version['stdout'] | default('Not available', true) }}"
    short: False
  - title: Log
    value: "{{ ansible_log_url_msg if jenkins_build_url else 'Not available' }}"
    short: False
  - title: Deployer
    value: "{{ hostvars[cloud_env].ansible_host if cloud_env in groups['all'] else 'NA' }}"
    short: True
  - title: cloudsource
    value: "{{ cloudsource }}"
    short: True
  - title: Input model
    value: "{{ rc_im_name }}"
    short: True
  - title: SES enabled
    value: "{{ _msg_ses_enabled }}"
    short: True
  - title: Status
    value: "{{ rc_state }}"
    short: True

_field_mu:
  - title: MU
    value: "{{ maint_updates | default('') }}"
    short: True
_mu_available: "{{ maint_updates is defined and maint_updates | length > 0 }}"
_msg_field_mu: "{{ _mu_available | ternary(_field_mu, []) }}"

_field_clm:
  - title: CLM
    value: "{{ clm_model | title }}"
    short: True

_field_nodes_values:
  default: |
    Controllers: {{ controllers }}
    Computes: {{ computes}} (SLES) / {{ rhel_computes }} (RHEL)
  mid-scale-kvm: |
    Core: {{ core_nodes }}
    LMM: {{ lmm_nodes }}
    DBMQ: {{ dbmq_nodes }}
    SWIFT: {{ swift_nodes }}
    NEUTRON: {{ neutron_nodes }}
    Computes: {{ computes}} (SLES) / {{ rhel_computes }} (RHEL)
  entry-scale-kvm-mml: |
    Core: {{ core_nodes }}
    LMM: {{ lmm_nodes }}
    DBMQ: {{ dbmq_nodes }}
    Computes: {{ computes}} (SLES) / {{ rhel_computes }} (RHEL)

_field_nodes:
  - title: Nodes
    value: "{{ _field_nodes_values[scenario_name] | default(_field_nodes_values['default']) }}"
    short: False

_msg_field_clm_nodes: "{{ (scenario_name is defined) | ternary(_field_nodes + _field_clm, []) }}"
