#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
  product:
    version: 2

  network-groups:
    - name: ARDANA
      hostname-suffix: ardana

    - name: HOSTNAME
      hostname-suffix: host

    - name: MANAGEMENT
      hostname-suffix: mgmt
      hostname: true
      tags:
        - neutron.networks.vlan:
            provider-physical-network: physnet1
      tls-component-endpoints:
        - barbican-api
        - mysql
        - rabbitmq
      component-endpoints:
        - default
      routes:
        - OCTAVIA-MGMT-NET
        - default
      load-balancers:
        - internal-lb

    - name: TENANT-VLAN
      hostname-suffix: tvlan
      tags:
        - neutron.networks.vlan:
            provider-physical-network: physnet2
            tenant-vlan-id-range: 1000:1100

    - name: SWIFT
      hostname-suffix: swift
      component-endpoints:
        - swift-container
        - swift-account
        - swift-object
        - swift-rsync

    - name: ISCSI
      hostname-suffix: iscsi
      component-endpoints:
        - vsa

    - name: GUEST
      hostname-suffix: guest
      tags:
        - neutron.networks.vxlan

    - name: EXTERNAL-API
      hostname-suffix: extapi
      load-balancers:
        - external-lb

    - name: EXTERNAL-VM
      tags:
        - neutron.l3_agent.external_network_bridge
