#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Limited to the deployer
---

- name: deployer-rhel-repo | download_suse_centos_artifacts | Create dir for
        downloaded rpms and all rpms
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ centos_rpms_download_location }}"
    - "{{ centos_all_rpms_location }}"

- name: deployer-rhel-repo | download_suse_centos_artifacts | Refresh suse centos repo
  become: yes
  shell: |
     set -eu
     zypper --non-interactive refresh {{ centos_repository_name }}

- name: deployer-rhel-repo | download_suse_centos_artifacts | Install RHEL venv on deployer
  become: yes
  command: >
     zypper install --no-confirm --from {{ centos_repository_name }} {{ item }}
  with_items: "{{ rhel_venv_rpms_list }}"
  register: _centos_venv_rpms_install_result

- name: deployer-rhel-repo | download_suse_centos_artifacts | Rebuild rhel venv index
  become: yes
  command: >
    ./create_index
    --dir={{ PACKAGE_CONSTANTS.REPO_DIR }}/{{ ardana_version }}/rhel_venv/x86_64
  args:
    chdir: "{{ 'packager' | bin_dir if deployer_media_legacy_layout|bool else '/usr/bin/' }}"
  when: _centos_venv_rpms_install_result | changed

- name: deployer-rhel-repo | download_suse_centos_artifacts | Download rpms on deployer
  command: zypper download {{ centos_repository_name }}:{{ item }}
  with_items: "{{ rhel_repo_rpms_list }}"
  register: _centos_repo_rpms_download_result

- name: deployer-rhel-repo | download_suse_centos_artifacts | Identify downloaded rpms path
  become: yes
  shell: |
    set -eu
    find "{{ardanauser_home}}/.cache/zypp/packages/{{centos_repository_name}}" -path "*/{{ item }}-*.rpm"
  with_items: "{{ rhel_repo_rpms_list }}"
  register: _rpm_download_path_result

- name: deployer-rhel-repo | download_suse_centos_artifacts | Create download paths item
  set_fact:
    _d_rpms_item: "{{ item.stdout_lines | default([])}}"
  with_items: "{{ _rpm_download_path_result.results }}"
  register: _d_rpms_list_result

- name: deployer-rhel-repo | download_suse_centos_artifacts | Create all download paths list
  set_fact:
    _downloaded_rpms_list: "{{ _d_rpms_list_result.results | map(attribute='ansible_facts._d_rpms_item') | list }}"
  with_items: "{{ _d_rpms_list_result.results }}"

- debug:
    var: _downloaded_rpms_list

- name: deployer-rhel-repo | download_suse_centos_artifacts | Copy centos downloaded rpms
        to local download directory
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ centos_rpms_download_location }}/"
  with_items: "{{ _downloaded_rpms_list }}"
  when: _downloaded_rpms_list | length > 0

- name: deployer-rhel-repo | download_suse_centos_artifacts | Copy downloaded rpms
        to all rpms work directory
  copy:
    src: "{{ item }}"
    dest: "{{ centos_all_rpms_location }}/"
  with_fileglob:
    - "{{ centos_rpms_download_location }}/*.rpm"

