#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

os_health_build_name: "{{ ardana_env }}_qa_{{ test_name }}"
ardana_qe_test_log_url: "{{ lookup('env', 'BUILD_URL') }}artifact/.artifacts/{{ test_name }}.log"
ardana_qe_test_log_url_msg: "[{{ ardana_qe_test_log_url }}]({{ ardana_qe_test_log_url }})"

rc_att_colapsed: True

rc_msg_color: "{{ 'danger' if (rc_state == 'Failed' and ardana_qe_test_results is not defined) else '#BDC3C7' if rc_state == 'Started' else _test_msg_color }}"
_test_msg_color: "{{ (ardana_qe_test_results is defined and ardana_qe_test_results.failed | int > 0) | ternary('warning', 'good') }}"

rc_announcement_started: "Running QA test - {{ test_name }}"
rc_announcement_finished: "{{ rc_previous_announcement.content | b64decode if rc_previous_announcement.content is defined else 'NA' }}"

rc_msg_title: "QA test - {{ test_name }}: {{ rc_state }}"

rc_msg_fields_started:
  - title: Started by
    value: "{{ jenkins_build_url_msg  }}"
    short: False
  - title: Deployer
    value: "{{ hostvars[ardana_env].ansible_host }}"
    short: True

_rc_msg_fields_finished:
  - title: Started by
    value: "{{ jenkins_build_url_msg }}"
    short: False
  - title: Deployer
    value: "{{ hostvars[ardana_env].ansible_host }}"
    short: True
  - title: Total
    value: "{{ ardana_qe_test_results.total if ardana_qe_test_results is defined else 'Not available' }}"
    short: True
  - title: Passed
    value: "{{ ardana_qe_test_results.passed if ardana_qe_test_results is defined else 'Not available' }}"
    short: True
  - title: Failed
    value: "{{ ardana_qe_test_results.failed if ardana_qe_test_results is defined else 'Not available' }}"
    short: True
  - title: Skipped
    value: "{{ ardana_qe_test_results.skipped if ardana_qe_test_results is defined else 'Not available' }}"
    short: True
  - title: Failed tests
    value: "{{ ardana_qe_failed_tests.stdout if ardana_qe_failed_tests is defined else 'Timeout' if test_output is defined and test_output.rc == 124 else 'Not available' }}"
    short: False
  - title: Log
    value: "{{ ardana_qe_test_log_url_msg if lookup('env', 'BUILD_URL') else 'Not available' }}"
    short: False

_rc_os_health_msg:
  - title: OpenStack-Health
    value: "[{{ os_health_url }}]({{ os_health_url }})"
    short: False

rc_msg_fields_finished: "{{ _rc_msg_fields_finished + _rc_os_health_msg if subunit is defined and subunit.stat.exists else _rc_msg_fields_finished }}"
