#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
  product:
    version: 2
  cloud:
    name: {{ scenario['cloud_name'] }}
    hostname-data:
        host-prefix: {{ 'ardana-' ~ qe_env if qe_env is defined else 'ardana' }}
        member-prefix: -m
    ntp-servers:
{% for server in scenario['ntp_servers'] %}
      - {{ server }}
{% endfor %}
    dns-settings:
      nameservers:
{% for server in scenario.nameservers %}
        - {{ server }}
{% endfor %}

    firewall-settings:
        enable: true
        # log dropped packets
        logging: true

    # Disc space needs to be allocated to the audit directory before enabling
    # auditing.
    # Default can be either "disabled" or "enabled". Services listed in
    # "enabled-services" and "disabled-services" override the default setting.
    audit-settings:
       audit-dir: /var/audit
       default: {{ 'enabled' if scenario['audit_enabled'] else 'disabled' }}
       #enabled-services:
       #  - keystone
       #  - barbican
       #disabled-services:
       #  - nova
       #  - barbican
       #  - keystone
       #  - cinder
       #  - ceilometer
       #  - neutron
       #  - swift
