#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
cloud_env: localhost

cloudsource: stagingcloud9

# cloud product can be ardana or crowbar
cloud_product: "ardana"

cloud_admin_user:
  ardana: ardana
  crowbar: root

# The cloud release is encoded in the cloudsource value
cloud_release: "cloud{{ cloudsource | regex_search('\\d') }}"
cloud_git_branch:
  cloud8: "stable/pike"
  cloud9: "master"

clouddata_server: "provo-clouddata.cloud.suse.de"
sles_media_server: "ibs-mirror.prv.suse.net"

rhel_enabled: "{{ rhel_computes is defined and rhel_computes | int > 0 }}"
ses_enabled: False
ses_rgw_enabled: False
ardana_ses_integration_version: 2
cinder_lvm_enabled: '{{ not ses_enabled }}'

ardana_nova_migrate_enabled: True

workspace_path: "{{ lookup('env', 'WORKSPACE') | default(playbook_dir, true) }}"
input_model_path: "{{ workspace_path }}/input_model"

automation_scripts_path: "{{ playbook_dir }}/../../.."

is_physical_deploy: "{{ cloud_env in groups['qe_all'] }}"
rc_notify: False
rc_notify_start: True

suse_release: "suse-{{ ansible_distribution_version }}"
local_repos_web_dir_prefix: "{{ (cloud_product == 'crowbar') | ternary('tftpboot', 'www') }}"
local_repos_base_dir: "/srv/{{ local_repos_web_dir_prefix }}/{{ suse_release }}/{{ ansible_architecture }}/repos"

sles_cloud_version:
  "12.3": 8
  "12.4": 9


# This variable controls the OS type and version used for Ardana RHEL compute nodes
# Possible values: CentOS_73, CentOS_75, RHEL_73, RHEL_75
rhel_os: CentOS_75
rhel_os_version: "{{ rhel_os.split('_')[1] }}"

ipv6: False

updates_test_enabled: False

reboot_after_deploy: False

update_after_deploy: False
maintenance_updates_path:
  Cloud: "SUSE_Updates_{{ cloud_repo_path|default('OpenStack-Cloud') }}_{{ sles_cloud_version[ansible_distribution_version]|default('9') }}_x86_64"
  SLES: "SUSE_Updates_SLE-SERVER_{{ ansible_distribution_major_version }}-SP{{ ansible_distribution_release }}_x86_64"

maint_updates_list: "{{ maint_updates.split(',') if maint_updates is defined and maint_updates | length else [] }}"
maintenance_updates_server: "dist.suse.de"

sles_sdk_repos:
  - name: "SLE{{ ansible_distribution_major_version }}-SP{{ ansible_distribution_release }}-SDK-Pool"
  - name: "SLE{{ ansible_distribution_major_version }}-SP{{ ansible_distribution_release }}-SDK-Updates"
  - name: "SLE{{ ansible_distribution_major_version }}-SP{{ ansible_distribution_release }}-SDK-Updates-test"
    enabled: "{{ updates_test_enabled }}"

ntp_servers:
  - 10.86.32.1
  - nsprv.provo.novell.com
  - ntp.suse.de
  - ntp0.suse.de
  - ntp1.suse.de
  - ntp2.suse.de
  - ntp3.suse.de
  - kirk.provo.novell.com
  - 1.us.pool.ntp.org
  - 2.us.pool.ntp.org

dns_servers:
  - 10.84.2.20
  - 10.84.2.21

rc_channels:
  pcloud001: "cloud-qe-pcloud001"
  pcloud002: "cloud-qe-pcloud002"
  qe002: "cloud-qe-hlm002"
  qe007: "cloud-qe-hlm007"
  qe101: "cloud-qe-hlm101"
  qe102: "cloud-qe-hlm102"
  qe201: "cloud-qe-hlm201"
  qe202: "cloud-qe-hlm202"
  qe2023: "cloud-qe-hlm2023par"
  qescale: "cloud-qe-scale"
  engcloud-ci-slot16: "cloud-maintenance"
  engcloud-ci-slot17: "cloud-maintenance"
  engcloud-ci-slot18: "cloud-ci-monitoring"
  engcloud-ci-slot19: "cloud-ci-monitoring"
  engcloud-ci-slot20: "cloud-ci-monitoring"
  engcloud-ci-slot21: "cloud-ci-monitoring"
