#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
  product:
    version: 2

  interface-models:
    - name: ARDANA-INTERFACES
      network-interfaces:

        - name: hed1
          device:
            name: hed1
          network-groups:
            - MANAGEMENT

        - name: hed2
          device:
            name: hed2
          network-groups:
            - ARDANA

        - name: hed8
          device:
            name: hed8
          forced-network-groups:
            - HOSTNAME


    - name: CONTROLLER-INTERFACES
      network-interfaces:

        - name: hed2
          device:
            name: hed2
          network-groups:
            - ARDANA

        - name: BOND0
          device:
              name: bond0
          bond-data:
             options:
                 mode: active-backup
                 miimon: 200
                 primary: hed1
             provider: linux
             devices:
               - name: hed1
               - name: hed3
          network-groups:
            - MANAGEMENT

        - name: hed4
          device:
            name: hed4
          network-groups:
            - EXTERNAL-VM

        - name: hed5
          device:
            name: hed5
          network-groups:
            - GUEST

        - name: hed6
          device:
            name: hed6
          network-groups:
            - SWIFT
          forced-network-groups:
            - ISCSI

        - name: hed7
          device:
            name: hed7
          network-groups:
            - TENANT-VLAN

        - name: hed8
          device:
            name: hed8
          forced-network-groups:
            - HOSTNAME
          network-groups:
            - EXTERNAL-API

    - name: COMPUTE-INTERFACES
      network-interfaces:

        - name: hed1
          device:
            name: hed1
          network-groups:
            - MANAGEMENT

        - name: hed2
          device:
            name: hed2
          network-groups:
            - ARDANA

        - name: hed4
          device:
            name: hed4
          network-groups:
            - EXTERNAL-VM

        - name: hed5
          device:
            name: hed5
          network-groups:
            - GUEST

        - name: hed6
          device:
            name: hed6
          forced-network-groups:
            - ISCSI

        - name: hed7
          device:
            name: hed7
          network-groups:
            - TENANT-VLAN

        - name: hed8
          device:
            name: hed8
          forced-network-groups:
            - HOSTNAME
